collections:
  paintings:
    output: true
    order:
      - peeb.md
      - missing-dog.md
      - untitled-i.md
      - mouths.md
      - seal.md
      - pigeons.md
      - boy.md
      - untitled-ii.md
      - ih.md
      - a-swim.md
      - dreams.md
      - scary-monsters.md
      - lights.md
  artists:
    output: true

defaults:
  - scope:
      path: ""
      type: "paintings"
    values:
      layout: "painting"
  - scope:
      path: ""
      type: "artists"
    values:
      layout: "artist"
  - scope:
      path: ""
    values:
      layout: "default"
